### ISSUE TITLE
i caught this error dude.. please fix this error dude...

### ISSUE THREAD

**Issue by randyaries** [reynaldiaznan123/cycoder-server#1]
```shell
(node:20092) UnhandledPromiseRejectionWarning: Error: Cannot add route when fastify instance is already started!
    at throwIfAlreadyStarted (D:\WEB APPS\TEMPLATE\socket-server\node_modules\fastify\fastify.js:360:40)
    at Object.route (D:\WEB APPS\TEMPLATE\socket-server\node_modules\fastify\lib\route.js:123:5)
    at Object.prepareRoute (D:\WEB APPS\TEMPLATE\socket-server\node_modules\fastify\lib\route.js:115:18)
    at Object._post [as post] (D:\WEB APPS\TEMPLATE\socket-server\node_modules\fastify\fastify.js:204:34)
    at D:\WEB APPS\TEMPLATE\socket-server\node_modules\cycoder-server\dist\subscribers\http-subscriber.js:49:26
    at new Promise (<anonymous>)
    at HttpSubscriber.subscribe (D:\WEB APPS\TEMPLATE\socket-server\node_modules\cycoder-server\dist\subscribers\http-subscriber.js:48:16)
    at D:\WEB APPS\TEMPLATE\socket-server\node_modules\cycoder-server\dist\index.js:148:35
    at Array.map (<anonymous>)
    at D:\WEB APPS\TEMPLATE\socket-server\node_modules\cycoder-server\dist\index.js:147:43
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not han
dled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 2)
(node:20092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-12-26T04:08:10.873Z] - -oCwFEX52KZsuu40AAAB joined channel: lontong
```

**Comment by reynaldiaznan123** [comment]
Ok fixed... Please check and install again
